Repository RomaZherko21/NoName, pull requests merged in 2023-01, with the labels that each got.

#19 feat(BE-2): get user by id enpoint
  client/package.json
  client/src/pages/Users/model/filters.tsx
  client/src/services/nodeApi/users.ts
  client/src/shared/helpers/parse.ts
  client/yarn.lock
  server/src/posts/handler.ts
  server/src/routes.ts
  server/src/users/handler.ts
  server/src/users/queries.ts
Labels: enhancement

#20 refactor(BE-3): change status from 200 to 204
  server/src/posts/handler.ts
  server/src/user/handler.ts
  server/src/users/handler.ts
Labels: enhancement

#14 feat(FE-26): add post page
  client/public/locales/en/page.json
  client/public/locales/en/post.json
  client/public/locales/en/translation.json
  client/src/app/Router.tsx
  client/src/pages/404/404.tsx
  client/src/pages/Post/Post.tsx
  client/src/pages/Post/Styles.module.scss
  client/src/pages/Post/index.ts
  client/src/pages/Post/model/Post.model.ts
  client/src/pages/Post/model/index.ts
  client/src/pages/Posts/Posts.tsx
  client/src/pages/Posts/ui/PopupConfig.tsx
  client/src/pages/index.ts
  client/src/services/nodeApi/post.ts
  client/src/services/nodeApi/users.ts
  client/src/shared/consts/routes.ts
Labels: enhancement

#25 fix(FE-27): remove redunant margin
  client/src/shared/ui/CommonCard/CommonCard.tsx
Labels: enhancement

#23 Fe 23 add filters to posts page
  client/public/locales/en/translation.json
  client/src/pages/Post/PopupConfig.tsx
  client/src/pages/Post/Post.tsx
  client/src/pages/Posts/Posts.tsx
  client/src/pages/Posts/model/filters.ts
  client/src/pages/Posts/model/index.ts
  client/src/pages/Posts/ui/CommonCard/CommonCard.tsx
  client/src/pages/Posts/ui/CommonCard/PopupConfig.tsx
  client/src/pages/Posts/ui/CommonCard/Styles.module.scss
  client/src/pages/Posts/ui/CommonCard/index.ts
  client/src/pages/Posts/ui/index.ts
  client/src/pages/Profile/ui/Timeline/Timeline.tsx
  client/src/pages/Profile/ui/Timeline/ui/Post/PopupConfig.tsx
  client/src/pages/Profile/ui/Timeline/ui/Post/Post.tsx
  client/src/pages/Profile/ui/Timeline/ui/Post/Styles.module.scss
  client/src/pages/Profile/ui/Timeline/ui/Post/index.ts
  client/src/pages/Profile/ui/Timeline/ui/index.ts
  client/src/shared/ui/Pagination/Pagination.tsx
  client/src/shared/ui/PopupMenu/PopupMenu.tsx
  client/src/shared/ui/index.ts
Labels: enhancement

#24 feat(FE-30): add toastify to account users and posts pages
  client/public/locales/en/notification.json
  client/src/pages/Account/ui/General/ProfileForm/ProfileForm.tsx
  client/src/pages/Posts/ui/CreatePostForm/CreatePostForm.tsx
  client/src/pages/Posts/ui/PopupConfig.tsx
  client/src/pages/Users/Users.tsx
Labels: enhancement

#27 fix(FE-31): fix spinner in posts
  client/src/pages/Posts/Posts.tsx
Labels: bug

#28 feat(FE-32): add button read more to posts
  client/public/locales/en/post.json
  client/src/pages/Posts/ui/CommonCard/CommonCard.tsx
Labels: enhancement

#29 feat(FE-19): add mui skeleton
  client/src/pages/Posts/Posts.tsx
  client/src/pages/Posts/ui/PostLoader/PostLoader.tsx
  client/src/pages/Posts/ui/PostLoader/index.ts
  client/src/pages/Posts/ui/index.ts
Labels: enhancement

#30 refactor(FE-28): change upload icon in add post
  client/public/locales/en/post.json
  client/src/pages/Posts/ui/CreatePostForm/CreatePostForm.tsx
Labels: documentation

#31 feat(BE-0): add likes system
  MySQL/setup.sql
  client/src/models/User.ts
  client/src/pages/Posts/model/Posts.model.ts
  client/src/services/nodeApi/post.ts
  client/src/services/nodeApi/user.ts
  server/src/auth/handler.ts
  server/src/middlewares/useAuth.ts
  server/src/models/user.ts
  server/src/posts/handler.ts
  server/src/routes.ts
  server/src/user/handler.ts
  server/src/users/handler.ts
Labels: enhancement

#32 feat(FE-24): add likes to post
  client/src/pages/Post/Post.tsx
  client/src/pages/Post/model/Post.model.ts
  client/src/pages/Posts/Posts.tsx
  client/src/pages/Posts/model/Posts.model.ts
  client/src/pages/Posts/ui/CommonCard/CommonCard.tsx
  client/src/services/nodeApi/post.ts
  client/src/shared/types/post.ts
  server/src/posts/handler.ts
Labels: enhancement

#33 feat(FE-32): add filters to posts page
  client/package.json
  client/public/locales/en/post.json
  client/public/locales/en/translation.json
  client/public/locales/en/user.json
  client/src/pages/Books/Books.tsx
  client/src/pages/Books/model/filters.tsx
  client/src/pages/Posts/Posts.tsx
  client/src/pages/Posts/model/filters.ts
  client/src/pages/Subscribers/Subscribers.tsx
  client/src/pages/Subscribers/model/filters.tsx
  client/src/pages/Users/Users.tsx
  client/src/pages/Users/model/filters.tsx
  client/src/shared/helpers/parse.ts
  client/src/shared/ui/AsideFilters/AsideFilters.tsx
  client/src/shared/ui/AsideFilters/AsideFiltersBar.tsx
  client/src/shared/ui/Filters/CheckBoxFilter.tsx
  client/src/shared/ui/Filters/DatePickerFilter.tsx
  client/src/shared/ui/Filters/index.ts
  client/src/shared/ui/index.ts
  client/yarn.lock
Labels: enhancement

#36 feat(FE-36): add functionality to comments
  client/public/locales/en/post.json
  client/src/pages/Post/Post.tsx
  client/src/pages/Post/model/Post.model.ts
  client/src/pages/Post/ui/Comment/Comment.tsx
  client/src/pages/Post/ui/CommentPopupConfig.tsx
  client/src/pages/Post/ui/index.ts
  client/src/services/nodeApi/post.ts
  client/src/shared/types/post.ts
  client/src/shared/ui/Form/InputField/InputField.tsx
  client/src/shared/ui/PopupMenu/PopupMenu.tsx
  server/src/posts/handler.ts
Labels: enhancement

#41 feat(FE-39): refactor 404 page
  client/src/assets/images/404.png
  client/src/assets/images/404.svg
  client/src/pages/404/404.tsx
Labels: enhancement

#42 Fe 42 refactor and new post page
  client/public/locales/en/notification.json
  client/public/locales/en/page.json
  client/public/locales/en/post.json
  client/public/locales/en/translation.json
  client/src/app/Router.tsx
  client/src/app/theme/dark.ts
  client/src/pages/Account/ui/General/ProfileForm/ProfileForm.tsx
  client/src/pages/CreatePost/CreatePost.tsx
  client/src/pages/CreatePost/index.ts
  client/src/pages/CreatePost/model/CreatePost.model.ts
  client/src/pages/CreatePost/model/index.ts
  client/src/pages/CreatePost/ui/PostCover/PostCover.tsx
  client/src/pages/CreatePost/ui/PostCover/Styles.module.scss
  client/src/pages/CreatePost/ui/PostCover/index.ts
  client/src/pages/CreatePost/ui/QuillField/QuillField.tsx
  client/src/pages/CreatePost/ui/QuillField/_textEditor.scss
  client/src/pages/CreatePost/ui/QuillField/index.ts
  client/src/pages/CreatePost/ui/index.ts
  client/src/pages/Posts/ui/CreatePostForm/CreatePostForm.tsx
  client/src/pages/Posts/ui/PopupConfig.tsx
  client/src/pages/Users/Users.tsx
  client/src/pages/index.ts
Labels: feat
